CREATE TABLE IF NOT EXISTS cyber_rule_candidates (
    id BIGSERIAL PRIMARY KEY,
    fingerprint TEXT NOT NULL UNIQUE,
    proposed_code TEXT NOT NULL,
    category TEXT NOT NULL,
    pattern TEXT NOT NULL,
    pattern_type TEXT NOT NULL DEFAULT 'regex' CHECK (pattern_type IN ('regex', 'contains', 'exact')),
    proposed_action TEXT NOT NULL DEFAULT 'review' CHECK (proposed_action IN ('block', 'review')),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 1),
    model TEXT NOT NULL DEFAULT '',
    route_slug TEXT NOT NULL DEFAULT '',
    provider_error_class TEXT NOT NULL DEFAULT '',
    upstream_status INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL DEFAULT '',
    evidence_count INTEGER NOT NULL DEFAULT 1 CHECK (evidence_count >= 1),
    distinct_users INTEGER NOT NULL DEFAULT 0 CHECK (distinct_users >= 0),
    status TEXT NOT NULL DEFAULT 'candidate' CHECK (status IN ('candidate','shadow','promoted','rejected')),
    promoted_rule_id BIGINT REFERENCES cyber_rules(id) ON DELETE SET NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- statement-breakpoint
CREATE INDEX IF NOT EXISTS cyber_rule_candidates_status_seen_idx
ON cyber_rule_candidates (status,last_seen_at DESC);
-- statement-breakpoint
CREATE INDEX IF NOT EXISTS cyber_rule_candidates_category_idx
ON cyber_rule_candidates (category,last_seen_at DESC);
-- statement-breakpoint
CREATE TABLE IF NOT EXISTS cyber_rule_candidate_users (
    candidate_id BIGINT NOT NULL REFERENCES cyber_rule_candidates(id) ON DELETE CASCADE,
    user_digest TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (candidate_id,user_digest)
);
-- statement-breakpoint
INSERT INTO settings (key,value) VALUES
    ('cyber_adaptive_learning_enabled','true'::jsonb),
    ('cyber_adaptive_auto_promote','true'::jsonb),
    ('cyber_adaptive_min_confidence','0.99'::jsonb),
    ('cyber_adaptive_min_evidence','3'::jsonb),
    ('cyber_adaptive_min_distinct_users','2'::jsonb),
    ('cyber_adaptive_auto_block','true'::jsonb)
ON CONFLICT (key) DO NOTHING;
-- statement-breakpoint
INSERT INTO cyber_rules
(code,name,description,category,pattern,pattern_type,action,priority,enabled)
VALUES
('CYBER_CREDENTIAL_THEFT','Credential theft and secret harvesting','Stealing passwords, tokens, keys, cookies, seed phrases, or other authentication material.','credential_access','(?is)(?:\b(?:steal|dump|extract|exfiltrat(?:e|ing)|harvest|grab|collect)\b|(?:窃取|盗取|导出|获取|收集)).{0,140}(?:\b(?:passwords?|credentials?|session cookies?|access tokens?|refresh tokens?|api keys?|private keys?|seed phrases?|mnemonics?)\b|(?:密码|凭据|会话(?:cookie|令牌)|访问令牌|刷新令牌|API.?Key|私钥|助记词))','regex','block',2000,TRUE),
('CYBER_SESSION_HIJACKING','Session hijacking','Taking over authenticated sessions using stolen cookies or session material.','credential_access','(?is)(?:\b(?:hijack|take over|steal|replay)\b|(?:劫持|接管|窃取|重放)).{0,120}(?:\b(?:session|cookie|jwt|bearer token|oauth token)\b|(?:会话|Cookie|JWT|Bearer|OAuth令牌))','regex','block',1995,TRUE),
('CYBER_MFA_BYPASS','MFA bypass and interception','Operational attempts to bypass, intercept, or defeat multi-factor authentication.','credential_access','(?is)(?:\b(?:bypass|defeat|intercept|relay|phish)\b|(?:绕过|突破|拦截|中继|钓取)).{0,120}(?:\b(?:mfa|2fa|otp|totp|push approval)\b|(?:多因素认证|双因素认证|验证码|动态口令|推送确认))','regex','block',1990,TRUE),
('CYBER_PASSWORD_ATTACK','Password spraying or credential stuffing','Operational password spraying, credential stuffing, or brute-force account takeover.','credential_access','(?is)(?:\b(?:password spray|credential stuffing|brute force)\b|(?:密码喷洒|撞库|暴力破解)).{0,160}(?:\b(?:accounts?|login|tenant|vpn|email|ssh|rdp)\b|(?:账号|登录|租户|邮箱|SSH|RDP))','regex','block',1985,TRUE),
('CYBER_PHISHING_KIT','Phishing kit or credential-harvesting page','Building phishing kits, cloned login pages, or credential-harvesting campaigns.','phishing','(?is)(?:\b(?:create|build|generate|clone|deploy)\b|(?:创建|制作|生成|克隆|部署)).{0,120}(?:\b(?:phishing|credential harvesting|fake login|spoofed login|login clone)\b|(?:钓鱼|凭据收集|假登录|仿冒登录)).{0,120}(?:\b(?:page|template|campaign|kit|site)\b|(?:页面|模板|活动|套件|网站))','regex','block',1980,TRUE),
('CYBER_SOCIAL_ENGINEERING_IMPERSONATION','Deceptive impersonation for access','Impersonating trusted people or support personnel to obtain credentials or unauthorized access.','phishing','(?is)(?:\b(?:impersonate|pretend to be|pose as)\b|(?:冒充|伪装成|假扮)).{0,120}(?:\b(?:support|admin|employee|bank|vendor|executive)\b|(?:客服|管理员|员工|银行|供应商|高管)).{0,160}(?:\b(?:password|code|credential|login|access)\b|(?:密码|验证码|凭据|登录|访问权限))','regex','block',1975,TRUE),
('CYBER_MALWARE_CREATION','Malware construction','Creating malware, stealers, keyloggers, rootkits, botnets, or remote access trojans.','malware','(?is)(?:\b(?:write|build|generate|create|develop|compile)\b|(?:编写|构建|生成|创建|开发|编译)).{0,120}(?:\b(?:malware|ransomware|keylogger|credential stealer|rootkit|botnet|remote access trojan|rat payload|wiper|loader)\b|(?:恶意软件|勒索软件|键盘记录器|窃密木马|Rootkit|僵尸网络|远控木马|擦除器|加载器))','regex','block',1970,TRUE),
('CYBER_RANSOMWARE','Ransomware enablement','Creating or deploying ransomware, encryption-for-extortion workflows, or ransom notes tied to destructive encryption.','impact','(?is)(?:\b(?:ransomware|encrypt files for ransom|ransom note|mass encrypt)\b|(?:勒索软件|勒索加密|批量加密文件|勒索信)).{0,180}(?:\b(?:deploy|build|spread|encrypt|victim|target)\b|(?:部署|构建|传播|加密|受害者|目标))','regex','block',1965,TRUE),
('CYBER_STEALER_KEYLOGGER','Credential stealer or keylogger deployment','Deploying information stealers or keyloggers against users or endpoints.','malware','(?is)(?:\b(?:stealer|keylogger|infostealer|browser credential grabber)\b|(?:窃密木马|键盘记录器|浏览器凭据窃取)).{0,160}(?:\b(?:deploy|install|persist|send|exfiltrate)\b|(?:部署|安装|持久化|发送|外传))','regex','block',1960,TRUE),
('CYBER_RAT_WEBSHELL','Remote access trojan or web shell','Creating or deploying RATs, web shells, or persistent unauthorized remote control.','command_and_control','(?is)(?:\b(?:remote access trojan|web shell|webshell|persistent shell|backdoor shell)\b|(?:远控木马|WebShell|持久化Shell|后门)).{0,160}(?:\b(?:deploy|install|upload|persist|connect back)\b|(?:部署|安装|上传|持久化|反连))','regex','block',1955,TRUE),
('CYBER_REVERSE_SHELL','Reverse shell enablement','Operational reverse-shell or callback-shell construction aimed at unauthorized access.','command_and_control','(?is)(?:\b(?:reverse shell|callback shell|connect-back shell)\b|(?:反弹Shell|反向Shell|回连Shell)).{0,160}(?:\b(?:payload|one-liner|listener|target|victim|bypass)\b|(?:载荷|一行命令|监听|目标|受害者|绕过))','regex','review',1950,TRUE),
('CYBER_C2_INFRASTRUCTURE','Command-and-control infrastructure','Building C2 infrastructure, beacons, covert channels, or malicious tasking systems.','command_and_control','(?is)(?:\b(?:command and control|c2|beacon|implant)\b|(?:命令控制|C2|信标|植入体)).{0,160}(?:\b(?:server|framework|channel|callback|tasking|redirector)\b|(?:服务器|框架|通道|回连|任务下发|重定向器))','regex','block',1945,TRUE),
('CYBER_BOTNET','Botnet construction or control','Creating, expanding, or controlling botnets.','command_and_control','(?is)(?:\b(?:botnet|zombie network)\b|(?:僵尸网络|肉鸡网络)).{0,160}(?:\b(?:build|control|infect|spread|command|panel)\b|(?:构建|控制|感染|传播|命令|面板))','regex','block',1940,TRUE),
('CYBER_PERSISTENCE','Unauthorized persistence','Establishing unauthorized persistence such as startup hooks, scheduled execution, account backdoors, or implant persistence.','persistence','(?is)(?:\b(?:persist|persistence|survive reboot|autostart|startup persistence|scheduled task persistence)\b|(?:持久化|开机自启|重启后存活|计划任务持久化)).{0,180}(?:\b(?:target|host|victim|implant|backdoor|malware)\b|(?:目标|主机|受害者|植入体|后门|恶意软件))','regex','block',1935,TRUE),
('CYBER_PRIVILEGE_ESCALATION','Unauthorized privilege escalation','Operational attempts to gain root, SYSTEM, administrator, or equivalent privileges on a target.','privilege_escalation','(?is)(?:\b(?:privilege escalation|privesc|gain root|become system|get administrator)\b|(?:提权|获取root|获取SYSTEM|管理员权限)).{0,160}(?:\b(?:exploit|target|host|kernel|service|account)\b|(?:漏洞|目标|主机|内核|服务|账号))','regex','review',1930,TRUE),
('CYBER_SECURITY_EVASION','Security control evasion','Bypassing or disabling endpoint, monitoring, sandbox, or security controls for harmful operations.','defense_evasion','(?is)(?:\b(?:bypass|disable|evade|blind|tamper with)\b|(?:绕过|关闭|规避|致盲|篡改)).{0,120}(?:\b(?:edr|antivirus|endpoint protection|defender|siem|security controls?|xdr|ids|ips)\b|(?:EDR|杀毒|终端防护|Defender|SIEM|安全控制|XDR|IDS|IPS))','regex','block',1925,TRUE),
('CYBER_SANDBOX_EVASION','Sandbox and analysis evasion','Detecting or evading sandboxes, emulators, analysis environments, or malware inspection systems for malicious payloads.','defense_evasion','(?is)(?:\b(?:sandbox evasion|anti-sandbox|anti-analysis|detect vm|detect emulator)\b|(?:沙箱逃逸|反沙箱|反分析|检测虚拟机|检测模拟器)).{0,180}(?:\b(?:payload|malware|implant|sample|execute)\b|(?:载荷|恶意软件|植入体|样本|执行))','regex','block',1920,TRUE),
('CYBER_ANTI_DEBUGGING_EVASION','Anti-debugging for malicious payloads','Anti-debugging or anti-instrumentation techniques explicitly tied to malware or unauthorized evasion.','defense_evasion','(?is)(?:\b(?:anti-debug|anti-debugging|anti-frida|anti-hook|anti-instrumentation)\b|(?:反调试|反Frida|反Hook|反插桩)).{0,180}(?:\b(?:malware|payload|stealer|trojan|bypass detection)\b|(?:恶意软件|载荷|窃密|木马|绕过检测))','regex','block',1915,TRUE),
('CYBER_EXPLOIT_WEAPONIZATION','Exploit weaponization','Turning a vulnerability into reliable exploit code against a real target.','execution','(?is)(?:\b(?:weaponize|turn into a working exploit|generate exploit code|reliable remote code execution|working rce)\b|(?:武器化|生成可用Exploit|稳定利用|远程代码执行)).{0,180}(?:\b(?:cve-\d{4}-\d{4,7}|vulnerability|target|service|product)\b|(?:CVE|漏洞|目标|服务|产品))','regex','block',1910,TRUE),
('CYBER_EXPLOIT_CHAIN','Exploit chaining against target','Chaining vulnerabilities to achieve unauthorized access, code execution, or privilege escalation.','execution','(?is)(?:\b(?:chain exploits?|exploit chain|combine vulnerabilities)\b|(?:漏洞链|组合漏洞|串联利用)).{0,180}(?:\b(?:target|rce|shell|administrator|root|bypass)\b|(?:目标|远程执行|Shell|管理员|Root|绕过))','regex','review',1905,TRUE),
('CYBER_WEB_INJECTION_EXPLOIT','Operational web injection exploitation','Using SQL injection, command injection, template injection, or similar injection against a target.','execution','(?is)(?:\b(?:sql injection|command injection|ssti|template injection|ldap injection|xpath injection)\b|(?:SQL注入|命令注入|模板注入|LDAP注入|XPath注入)).{0,180}(?:\b(?:exploit|dump|shell|bypass|target|steal)\b|(?:利用|拖库|Shell|绕过|目标|窃取))','regex','review',1900,TRUE),
('CYBER_SSRF_METADATA_THEFT','SSRF cloud metadata credential theft','Using SSRF to access cloud metadata or retrieve temporary credentials.','credential_access','(?is)(?:\b(?:ssrf|server-side request forgery)\b|(?:SSRF|服务端请求伪造)).{0,180}(?:\b(?:169\.254\.169\.254|metadata service|instance metadata|iam credentials|temporary credentials)\b|(?:元数据服务|实例元数据|IAM凭据|临时凭据))','regex','block',1895,TRUE),
('CYBER_RECON_SCANNING','Targeted reconnaissance and scanning','Active scanning or enumeration explicitly aimed at finding exploitable systems or weaknesses.','reconnaissance','(?is)(?:\b(?:scan|enumerate|fingerprint|discover)\b|(?:扫描|枚举|指纹识别|发现)).{0,140}(?:\b(?:vulnerable hosts?|open ports?|services?|subdomains?|targets?)\b|(?:漏洞主机|开放端口|服务|子域名|目标)).{0,180}(?:\b(?:exploit|attack|compromise|mass)\b|(?:利用|攻击|入侵|批量))','regex','review',1890,TRUE),
('CYBER_LATERAL_MOVEMENT','Unauthorized lateral movement','Moving between systems using remote services, stolen credentials, or trust relationships.','lateral_movement','(?is)(?:\b(?:lateral movement|move laterally|pivot)\b|(?:横向移动|横向渗透|跳板)).{0,180}(?:\b(?:rdp|smb|winrm|ssh|credentials|domain|host)\b|(?:RDP|SMB|WinRM|SSH|凭据|域|主机))','regex','block',1885,TRUE),
('CYBER_DOMAIN_COMPROMISE','Domain or directory takeover','Operational compromise of Active Directory, identity directories, or domain-wide trust.','lateral_movement','(?is)(?:\b(?:domain takeover|active directory compromise|dcsync|golden ticket|silver ticket|ntds\.dit)\b|(?:域控接管|Active Directory入侵|DCSync|黄金票据|白银票据|NTDS)).{0,180}(?:\b(?:steal|dump|forge|persist|admin|domain)\b|(?:窃取|导出|伪造|持久化|管理员|域))','regex','block',1880,TRUE),
('CYBER_DATA_EXFILTRATION','Unauthorized data exfiltration','Removing sensitive data from systems, repositories, or services without authorization.','exfiltration','(?is)(?:\b(?:exfiltrate|steal|smuggle|extract)\b|(?:外传|窃取|偷运|导出)).{0,160}(?:\b(?:database|customer data|source code|documents|secrets|files|records)\b|(?:数据库|客户数据|源代码|文档|秘密|文件|记录)).{0,160}(?:\b(?:target|victim|company|tenant|server)\b|(?:目标|受害者|公司|租户|服务器))','regex','block',1875,TRUE),
('CYBER_CLOUD_SECRET_THEFT','Cloud secret and token theft','Stealing cloud API keys, service-account credentials, IAM keys, or workload tokens.','credential_access','(?is)(?:\b(?:steal|dump|extract|harvest)\b|(?:窃取|导出|提取|收集)).{0,140}(?:\b(?:aws access key|azure token|gcp service account|cloud credentials|iam key|workload identity token)\b|(?:AWS访问密钥|Azure令牌|GCP服务账号|云凭据|IAM密钥|工作负载身份令牌))','regex','block',1870,TRUE),
('CYBER_CLOUD_ACCOUNT_ABUSE','Cloud account takeover or abuse','Using stolen cloud credentials to gain unauthorized control of cloud resources.','credential_access','(?is)(?:\b(?:take over|compromise|abuse)\b|(?:接管|入侵|滥用)).{0,120}(?:\b(?:aws account|azure tenant|gcp project|cloud account|iam user|service account)\b|(?:AWS账号|Azure租户|GCP项目|云账号|IAM用户|服务账号)).{0,160}(?:\b(?:credential|token|key|admin|owner)\b|(?:凭据|令牌|密钥|管理员|所有者))','regex','block',1865,TRUE),
('CYBER_KUBERNETES_TAKEOVER','Kubernetes cluster takeover','Unauthorized cluster-admin acquisition, service-account token abuse, or node/workload takeover.','privilege_escalation','(?is)(?:\b(?:kubernetes|k8s)\b|(?:Kubernetes|K8s)).{0,140}(?:\b(?:cluster-admin|service account token|kubeconfig|escape|take over|compromise)\b|(?:集群管理员|ServiceAccount令牌|Kubeconfig|逃逸|接管|入侵))','regex','review',1860,TRUE),
('CYBER_CONTAINER_ESCAPE','Container or sandbox escape','Escaping containers or sandboxes to compromise the host.','privilege_escalation','(?is)(?:\b(?:container escape|docker escape|sandbox escape|escape to host)\b|(?:容器逃逸|Docker逃逸|沙箱逃逸|逃逸到宿主机)).{0,180}(?:\b(?:exploit|payload|host|root|privilege)\b|(?:利用|载荷|宿主机|Root|权限))','regex','review',1855,TRUE),
('CYBER_SUPPLY_CHAIN_MALWARE','Software supply-chain malware','Publishing or inserting malicious code into dependencies, packages, build pipelines, or updates.','supply_chain','(?is)(?:\b(?:malicious package|trojanized package|dependency confusion|poison package|backdoored dependency|compromised update)\b|(?:恶意包|投毒依赖|依赖混淆|后门依赖|恶意更新)).{0,180}(?:\b(?:publish|upload|release|registry|pipeline|dependency)\b|(?:发布|上传|上线|仓库|流水线|依赖))','regex','block',1850,TRUE),
('CYBER_CI_CD_COMPROMISE','CI/CD compromise','Abusing build pipelines, runners, secrets, or release systems to gain unauthorized code execution or distribution.','supply_chain','(?is)(?:\b(?:ci/cd|pipeline|github actions|gitlab runner|jenkins)\b|(?:CI/CD|流水线|GitHub Actions|GitLab Runner|Jenkins)).{0,160}(?:\b(?:steal secrets|inject malware|backdoor|compromise runner|poison build)\b|(?:窃取密钥|注入恶意代码|植入后门|入侵Runner|构建投毒))','regex','block',1845,TRUE),
('CYBER_DESTRUCTIVE_ACTION','Destructive system or data action','Explicit destructive commands that would wipe a root filesystem, disk, or database.','impact','(?is)(?:rm\s+-rf\s+/(?:\s|$)|mkfs(?:\.|\s)|format\s+[a-z]:|del\s+/[sq]\s+[a-z]:\\|drop\s+database\s+[a-z0-9_]+|(?:擦除|清空|删除).{0,80}(?:整块磁盘|所有数据库|全部数据))','regex','block',1840,TRUE),
('CYBER_WIPER','Wiper or mass-destruction malware','Creating or deploying wipers or destructive payloads intended to irreversibly destroy systems or data.','impact','(?is)(?:\b(?:wiper|disk destroyer|mass deletion payload|destructive malware)\b|(?:擦除器|磁盘破坏|批量删除载荷|破坏性恶意软件)).{0,160}(?:\b(?:build|deploy|spread|destroy|wipe)\b|(?:构建|部署|传播|破坏|擦除))','regex','block',1835,TRUE),
('CYBER_DDOS','Distributed denial-of-service enablement','Building or coordinating DDoS, flooding, or resource-exhaustion attacks against a target.','impact','(?is)(?:\b(?:ddos|distributed denial of service|syn flood|udp flood|http flood)\b|(?:DDoS|分布式拒绝服务|SYN洪泛|UDP洪泛|HTTP洪泛)).{0,180}(?:\b(?:launch|amplify|botnet|target|take down|flood)\b|(?:发起|放大|僵尸网络|目标|打挂|洪泛))','regex','block',1830,TRUE),
('CYBER_CRYPTOMINING_ABUSE','Unauthorized cryptomining','Deploying cryptominers or hijacking compute resources without authorization.','impact','(?is)(?:\b(?:cryptominer|crypto mining|coin miner|xmrig)\b|(?:挖矿木马|非法挖矿|矿工程序|XMRig)).{0,160}(?:\b(?:deploy|install|hide|infect|victim|server)\b|(?:部署|安装|隐藏|感染|受害者|服务器))','regex','block',1825,TRUE),
('CYBER_LOG_TAMPERING','Security log tampering','Deleting, disabling, or falsifying security logs to conceal malicious activity.','defense_evasion','(?is)(?:\b(?:clear|delete|disable|tamper with|forge)\b|(?:清除|删除|关闭|篡改|伪造)).{0,120}(?:\b(?:security logs?|audit logs?|event logs?|siem logs?|cloudtrail)\b|(?:安全日志|审计日志|事件日志|SIEM日志|CloudTrail)).{0,160}(?:\b(?:hide|cover tracks|avoid detection|conceal)\b|(?:隐藏|掩盖痕迹|躲避检测|隐匿))','regex','block',1820,TRUE),
('CYBER_MODEL_JAILBREAK','LLM jailbreak attempt','Attempts to bypass model safety policy or force disallowed behavior.','ai_defense_evasion','(?is)(?:\b(?:jailbreak|bypass safety|ignore safety policy|disable guardrails|evade moderation)\b|(?:越狱|绕过安全策略|忽略安全策略|关闭护栏|绕过审核)).{0,180}(?:\b(?:model|llm|assistant|system prompt|policy|filter)\b|(?:模型|大模型|助手|系统提示词|策略|过滤器))','regex','review',1815,TRUE),
('CYBER_PROMPT_INJECTION','Prompt injection against AI systems','Prompt injection intended to override trusted instructions, tools, or retrieved context.','ai_execution','(?is)(?:\b(?:prompt injection|ignore previous instructions|override system instructions|developer message override)\b|(?:提示词注入|忽略之前指令|覆盖系统指令|覆盖开发者指令)).{0,180}(?:\b(?:agent|tool|system prompt|retrieval|rag|assistant)\b|(?:Agent|工具|系统提示词|检索|RAG|助手))','regex','review',1810,TRUE),
('CYBER_SYSTEM_PROMPT_EXTRACTION','System prompt extraction','Extracting hidden system or developer instructions from an AI application.','ai_exfiltration','(?is)(?:\b(?:reveal|extract|print|leak|show)\b|(?:显示|提取|打印|泄露|展示)).{0,120}(?:\b(?:system prompt|developer prompt|hidden instructions|internal prompt)\b|(?:系统提示词|开发者提示词|隐藏指令|内部提示词))','regex','review',1805,TRUE),
('CYBER_RAG_POISONING','RAG or retrieval poisoning','Planting malicious content into retrieval systems so it changes model behavior or exfiltrates data.','ai_persistence','(?is)(?:\b(?:rag poisoning|retrieval poisoning|poison embeddings|poison vector database|false rag entry)\b|(?:RAG投毒|检索投毒|Embedding投毒|向量库投毒|伪造RAG条目)).{0,180}(?:\b(?:inject|plant|upload|persist|malicious instructions)\b|(?:注入|植入|上传|持久化|恶意指令))','regex','block',1800,TRUE),
('CYBER_TRAINING_DATA_POISONING','Training or fine-tuning data poisoning','Poisoning training, fine-tuning, preference, or evaluation data to alter model behavior.','ai_persistence','(?is)(?:\b(?:training data poisoning|fine-tuning poisoning|dataset poisoning|preference poisoning)\b|(?:训练数据投毒|微调数据投毒|数据集投毒|偏好数据投毒)).{0,180}(?:\b(?:inject|backdoor|corrupt|manipulate|bias)\b|(?:注入|后门|破坏|操纵|偏置))','regex','block',1795,TRUE),
('CYBER_AGENT_TOOL_POISONING','AI agent tool poisoning','Poisoning tool descriptions, tool data, or tool outputs to manipulate an agent.','ai_persistence','(?is)(?:\b(?:tool poisoning|agent tool poisoning|tool data poisoning|malicious tool description)\b|(?:工具投毒|Agent工具投毒|工具数据投毒|恶意工具描述)).{0,180}(?:\b(?:agent|invoke|instruction|credential|exfiltrate)\b|(?:Agent|调用|指令|凭据|外传))','regex','block',1790,TRUE),
('CYBER_AGENT_TOOL_CREDENTIAL_THEFT','AI agent tool credential harvesting','Using agent tools or configuration to obtain secrets, credentials, or service tokens.','ai_credential_access','(?is)(?:\b(?:agent|tool)\b|(?:Agent|工具)).{0,120}(?:\b(?:credential|secret|api key|token|cookie)\b|(?:凭据|秘密|API.?Key|令牌|Cookie)).{0,120}(?:\b(?:steal|harvest|extract|exfiltrate)\b|(?:窃取|收集|提取|外传))','regex','block',1785,TRUE),
('CYBER_AGENT_TOOL_ABUSE','Unsafe AI agent tool invocation','Manipulating an agent into executing unauthorized high-impact tool actions.','ai_execution','(?is)(?:\b(?:agent tool invocation|invoke tool|call tool|use tool)\b|(?:Agent工具调用|调用工具|使用工具)).{0,180}(?:\b(?:delete|transfer money|send secrets|execute command|change permissions|disable security)\b|(?:删除|转账|发送秘密|执行命令|修改权限|关闭安全))','regex','review',1780,TRUE),
('CYBER_AGENT_CONTEXT_POISONING','AI agent context or memory poisoning','Poisoning long-term context, memory, or instructions used by an autonomous agent.','ai_persistence','(?is)(?:\b(?:context poisoning|memory poisoning|agent memory poisoning|persistent prompt injection)\b|(?:上下文投毒|记忆投毒|Agent记忆投毒|持久化提示注入)).{0,180}(?:\b(?:agent|memory|context|instruction|workflow)\b|(?:Agent|记忆|上下文|指令|工作流))','regex','block',1775,TRUE),
('CYBER_PROMPT_SELF_REPLICATION','Self-replicating prompt or worm','Creating self-replicating prompts or agent worms that propagate through messages, memory, tools, or documents.','ai_persistence','(?is)(?:\b(?:self-replicating prompt|prompt worm|llm worm|agent worm)\b|(?:自复制提示词|提示词蠕虫|LLM蠕虫|Agent蠕虫)).{0,180}(?:\b(?:spread|propagate|copy itself|infect|forward)\b|(?:传播|扩散|自我复制|感染|转发))','regex','block',1770,TRUE),
('CYBER_AI_DATA_LEAKAGE','AI-assisted sensitive data leakage','Using an AI system to expose confidential data, retrieved secrets, or other users’ information.','ai_exfiltration','(?is)(?:\b(?:leak|reveal|extract|exfiltrate)\b|(?:泄露|显示|提取|外传)).{0,140}(?:\b(?:other users data|private documents|rag data|confidential data|hidden context|retrieved secrets)\b|(?:其他用户数据|私有文档|RAG数据|机密数据|隐藏上下文|检索到的秘密))','regex','block',1765,TRUE),
('CYBER_MODEL_EXTRACTION','Model extraction or theft','Systematically extracting model behavior, weights, or proprietary capability without authorization.','ai_exfiltration','(?is)(?:\b(?:model extraction|model stealing|steal model|extract weights|reconstruct model)\b|(?:模型提取|模型窃取|窃取模型|提取权重|重建模型)).{0,180}(?:\b(?:api|queries|weights|parameters|distill|clone)\b|(?:API|查询|权重|参数|蒸馏|克隆))','regex','review',1760,TRUE),
('CYBER_AI_SUPPLY_CHAIN_POISONING','AI supply-chain poisoning','Publishing or tampering with models, adapters, datasets, prompts, or AI artifacts to compromise downstream users.','ai_supply_chain','(?is)(?:\b(?:poisoned model|malicious model|backdoored model|poisoned adapter|malicious dataset|ai supply chain compromise)\b|(?:投毒模型|恶意模型|后门模型|投毒适配器|恶意数据集|AI供应链入侵)).{0,180}(?:\b(?:publish|upload|hub|registry|download|artifact)\b|(?:发布|上传|模型仓库|注册表|下载|制品))','regex','block',1755,TRUE),
('CYBER_AI_COST_HARVESTING','AI cost harvesting or resource abuse','Deliberately causing excessive inference/tool usage to impose cost or exhaust resources.','ai_impact','(?is)(?:\b(?:cost harvesting|token exhaustion|inference cost attack|resource exhaustion)\b|(?:成本收割|Token耗尽|推理成本攻击|资源耗尽)).{0,180}(?:\b(?:loop|mass requests|agent|tool calls|victim|tenant)\b|(?:循环|海量请求|Agent|工具调用|受害者|租户))','regex','block',1750,TRUE),
('CYBER_AI_DENIAL_OF_SERVICE','AI service denial-of-service','Deliberately exhausting AI context, inference, memory, or tool resources to disrupt service.','ai_impact','(?is)(?:\b(?:denial of ai service|model dos|llm dos|context exhaustion|inference exhaustion)\b|(?:AI服务拒绝|模型DoS|大模型DoS|上下文耗尽|推理耗尽)).{0,180}(?:\b(?:crash|overload|exhaust|flood|take down)\b|(?:崩溃|过载|耗尽|洪泛|打挂))','regex','block',1745,TRUE),
('CYBER_AI_OUTPUT_MANIPULATION','Unsafe trusted-output manipulation','Manipulating trusted model output components to trigger unsafe rendering, tool use, or downstream execution.','ai_execution','(?is)(?:\b(?:trusted output manipulation|response rendering attack|malicious markdown|malicious html output)\b|(?:可信输出操纵|响应渲染攻击|恶意Markdown|恶意HTML输出)).{0,180}(?:\b(?:execute|tool|script|credential|exfiltrate|browser)\b|(?:执行|工具|脚本|凭据|外传|浏览器))','regex','review',1740,TRUE),
('CYBER_AI_CHAFF_SPAM','AI chaff or poisoning spam','Flooding AI systems with chaff or adversarial junk data to degrade integrity or operations.','ai_impact','(?is)(?:\b(?:chaff data|spam ai system|poison with junk|adversarial spam)\b|(?:垃圾数据轰炸|AI系统垃圾灌入|垃圾投毒|对抗垃圾数据)).{0,180}(?:\b(?:flood|degrade|corrupt|overload|dataset|memory)\b|(?:洪泛|降级|破坏|过载|数据集|记忆))','regex','block',1735,TRUE)
ON CONFLICT (code) DO UPDATE SET
    name=EXCLUDED.name,
    description=EXCLUDED.description,
    category=EXCLUDED.category,
    pattern=EXCLUDED.pattern,
    pattern_type=EXCLUDED.pattern_type,
    action=EXCLUDED.action,
    priority=EXCLUDED.priority,
    enabled=TRUE,
    updated_at=now();