from pathlib import Path

path = Path(__file__).resolve().parents[1] / "internal/platform/web/index.html"
text = path.read_text(encoding="utf-8")

def replace_once(old: str, new: str, label: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    text = text.replace(old, new, 1)

old_table = '''          const inputTokens=Number(item.metadata?.audit_input_tokens||item.metadata?.audit_requested_tokens||0);const contextTokens=Number(item.metadata?.audit_context_window_tokens||0);const overTokens=Number(item.metadata?.audit_tokens_over_limit||0);const tokenLine=inputTokens?`<span class="trace-subline mono">Tokens ${number(inputTokens)}${contextTokens?` / ${number(contextTokens)}`:''}${overTokens?` · 超 ${number(overTokens)}`:''}</span>`:'';\n          return `<tr><td><strong>${escapeHTML(detailedDateText(item.created_at))}</strong><span class="trace-subline">浏览器本地时间</span></td><td><span class="mono trace-request-id">${escapeHTML(item.request_id)}</span><span class="trace-subline mono">New API: ${escapeHTML(item.newapi_request_id||'-')}</span></td><td>${user}<span class="trace-subline">租户：${escapeHTML(tenant)}</span></td><td>${escapeHTML(item.source||'-')}<span class="trace-subline mono">${escapeHTML(item.route_slug||'-')}</span></td><td>${escapeHTML(item.model||'-')}<span class="trace-subline mono">${escapeHTML(item.endpoint||'-')}</span></td><td>${badge(item.decision||'unknown')}<span class="trace-subline mono">${escapeHTML(item.risk_code||'-')}</span></td><td><span class="trace-reason">${escapeHTML(reason)}</span>${errorClass?`<span class="trace-error-class">${escapeHTML(errorClass)}${item.metadata?.audit_http_status?` · HTTP ${escapeHTML(item.metadata.audit_http_status)}`:''}</span>`:''}${tokenLine}</td><td>HTTP ${item.http_status||'-'} / 上游 ${item.upstream_status||'-'}<span class="trace-subline">总计 ${number(item.latency_ms)} ms · 审计 ${number(item.audit_latency_ms)} ms</span><span class="trace-subline">模型调用 ${number(item.metadata?.audit_model_attempts||0)} · 重试 ${number(item.metadata?.audit_model_retries||0)} · 切换 ${number(item.metadata?.audit_fallback_count||0)}</span></td><td><button class="btn btn-small btn-secondary" type="button" data-trace-detail-index="${index}">详情</button></td></tr>`;\n'''
new_table = '''          const inputTokens=Number(item.metadata?.audit_input_tokens||item.metadata?.audit_requested_tokens||0);const contextTokens=Number(item.metadata?.audit_context_window_tokens||0);const overTokens=Number(item.metadata?.audit_tokens_over_limit||0);const tokenLine=inputTokens?`<span class="trace-subline mono">Tokens ${number(inputTokens)}${contextTokens?` / ${number(contextTokens)}`:''}${overTokens?` · 超 ${number(overTokens)}`:''}</span>`:'';\n          const requestSize=requestBodyDiagnostic(item);\n          return `<tr><td><strong>${escapeHTML(detailedDateText(item.created_at))}</strong><span class="trace-subline">浏览器本地时间</span></td><td><span class="mono trace-request-id">${escapeHTML(item.request_id)}</span><span class="trace-subline mono">New API: ${escapeHTML(item.newapi_request_id||'-')}</span></td><td>${user}<span class="trace-subline">租户：${escapeHTML(tenant)}</span></td><td>${escapeHTML(item.source||'-')}<span class="trace-subline mono">${escapeHTML(item.route_slug||'-')}</span></td><td>${escapeHTML(item.model||'-')}<span class="trace-subline mono">${escapeHTML(item.endpoint||'-')}</span></td><td>${badge(item.decision||'unknown')}<span class="trace-subline mono">${escapeHTML(item.risk_code||'-')}</span></td><td><span class="trace-reason">${escapeHTML(reason)}</span>${requestSize?`<span class="trace-error-class">请求体：${escapeHTML(requestSize)}</span>`:''}${errorClass?`<span class="trace-error-class">${escapeHTML(errorClass)}${item.metadata?.audit_http_status?` · HTTP ${escapeHTML(item.metadata.audit_http_status)}`:''}</span>`:''}${tokenLine}</td><td>HTTP ${item.http_status||'-'} / 上游 ${item.upstream_status||'-'}<span class="trace-subline">总计 ${number(item.latency_ms)} ms · 审计 ${number(item.audit_latency_ms)} ms</span><span class="trace-subline">模型调用 ${number(item.metadata?.audit_model_attempts||0)} · 重试 ${number(item.metadata?.audit_model_retries||0)} · 切换 ${number(item.metadata?.audit_fallback_count||0)}</span></td><td><button class="btn btn-small btn-secondary" type="button" data-trace-detail-index="${index}">详情</button></td></tr>`;\n'''
replace_once(old_table, new_table, "trace table current request size")

old_detail = '''          ['审计延迟',`${number(item.audit_latency_ms)} ms`], ['请求字节',number(item.request_bytes)], ['响应字节',number(item.response_bytes)],\n          ['审计输入 Tokens',item.metadata?.audit_input_tokens||item.metadata?.audit_requested_tokens||'-'], ['模型上下文上限',item.metadata?.audit_context_window_tokens||'-'], ['超出 Tokens',item.metadata?.audit_tokens_over_limit||'-'],\n'''
new_detail = '''          ['审计延迟',`${number(item.audit_latency_ms)} ms`], ['请求字节',byteText(item.request_bytes)], ['响应字节',byteText(item.response_bytes)],\n          ['请求体大小',item.metadata?.request_body_bytes?`${item.metadata.request_body_size_exact===true?'':'至少 '}${byteText(item.metadata.request_body_bytes)}`:'-'], ['平台请求体上限',byteText(item.metadata?.request_body_limit_bytes)], ['超出请求体上限',item.metadata?.request_body_over_limit_bytes?`${item.metadata.request_body_size_exact===true?'':'至少 '}${byteText(item.metadata.request_body_over_limit_bytes)}`:'-'], ['请求体大小是否精确',item.metadata?.request_body_limit_bytes?(item.metadata.request_body_size_exact===true?'是（Content-Length）':'否（安全下界）'):'-'],\n          ['审计输入 Tokens',item.metadata?.audit_input_tokens||item.metadata?.audit_requested_tokens||'-'], ['模型上下文上限',item.metadata?.audit_context_window_tokens||'-'], ['超出 Tokens',item.metadata?.audit_tokens_over_limit||'-'],\n'''
replace_once(old_detail, new_detail, "trace detail current request size")

path.write_text(text, encoding="utf-8")
